# fly.toml app configuration file generated for oc-notifier on 2024-11-26T10:58:57-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oc-notifier'
primary_region = 'atl'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  PHX_HOST = 'elgin-winter-shelter.org'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
